py_binary(
    name = "ci_report",
    srcs = ["ci_report.py"],
    deps = [
        "//lobster",
    ],
)

py_binary(
    name = "html_report",
    srcs = ["html_report.py"],
    deps = [
        "//lobster",
    ],
)

py_binary(
    name = "online_report",
    srcs = ["online_report.py"],
    deps = [
        "//lobster",
    ],
)

py_binary(
    name = "report",
    srcs = ["report.py"],
    deps = [
        "//lobster",
    ],
)
