filegroup(
    name = "assets",
    srcs = [
        "alert-triangle.svg",
        "award.svg",
        "check-square.svg",
        "chevron-down.svg",
        "external-link.svg",
        "link.svg",
        "menu.svg",
    ],
)
